### ISSUE TITLE
Faltan los esquemas de conexión (con fritzing o similar)

### ISSUE THREAD

**Issue by mlinaje** [DSHubicom/proyecto-dsh-descripcion-de-sistemas-ubicuos-18-19-smarthelper#1]
Faltan los esquemas de conexión (con fritzing o similar) para aquellos sitios donde se conectan dispositivos (e.g., nodemcu con sensor de oxígeno).
Añadidlo porfa (aquí y desde aquí podéis añadir la URL al blog)

**Comment by vzccristian** [comment]
Los esquemas de conexiones se encuentran dentro de la carpeta de MedidorOxigeno y DetectorBluetooth (aunque este último no son conexiones como tales).

**Comment by mlinaje** [comment]
Prefecto, subidlos al blog también. Todavía no he revisado a nivel de código los directorios
